#pragma once

#define MATER_RIGHT
#define SPLIT_LAYOUT
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_DRIVER SIOD0
#define SERIAL_USART_TIMEOUT 500
#define SPLIT_MAX_CONNECTION_ERRORS 0
#define FORCED_SYNC_THROTTLE_MS 100
#define SPLIT_CONNECTION_CHECK_TIMEOUT 10000

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 200U
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17

#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_FULL_DUPLEX TRUE
#define USB_SUSPEND_WAKEUP_DELAY 2000
#define SELECT_SOFT_SERIAL_SPEED 2
