#pragma once

#define EE_HANDS
#define SPLIT_LAYOUT
#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1
#define SERIAL_USART_DRIVER SIOD0
#define SERIAL_USART_TIMEOUT 5000
#define SPLIT_MAX_CONNECTION_ERRORS 50
#define FORCED_SYNC_THROTTLE_MS 100
#define SPLIT_CONNECTION_CHECK_TIMEOUT 0
